language: python

sudo: false

notifications:
  email: false

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libeigen3-dev
      - swig

python: 
  - '2.7'
  - '3.4'

before_install:
  - swig -version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install

script:
  - export "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/rdeits/swig-eigen-numpy/install/lib"
  - make
  - make install
  - cd ../python
  - python test_inverter.py
