language: python

# We need sudo to install a newer version of Eigen than the one supplied with Ubuntu 12.04
sudo: required

notifications:
  email: false

branches:
  only:
    - master

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - cmake
#       - libeigen3-dev
#       - swig

python:
  - '2.7'

before_install:
  - sudo apt-get update -qq
  - ./install_eigen.sh
  - swig -version
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install

script:
  - export "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/rdeits/swig-eigen-numpy/install/lib"
  - make
  - make install
  - cd ../python
  - python test_inverter.py
